### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by chainsx** [lzr936332553/yiban_Automation_tool#1]
首先感谢分享，然后有如下报错：
```
动态相关的网薪获取完成.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/yiban_Automation_tool/EGPA_script_random_num.py", line 70, in login
    start(start_json)
  File "/root/yiban_Automation_tool/EGPA_script_random_num.py", line 206, in start
    addTopic()
  File "/root/yiban_Automation_tool/EGPA_script_random_num.py", line 357, in addTopic
    link = Add_Topic.json()["data"]["link"]
KeyError: 'data'
```
在班级群发布**话题**和**投票**能够分别得到10网薪，不知道获取`学院id`和`班级id`是否为这个目的？

**Comment by chainsx** [comment]
好吧怪我没看代码emmm

**Comment by chainsx** [comment]
在函数中需要加入self？

**Comment by chainsx** [comment]
把data加上{}就没有报错，但是不知道是否解决了根本问题？
`["data"]`  > `[{"data"}]`
这样的话发现只有刷动态的功能，发话题和投票时会显示出错

**Comment by rick-lzr** [comment]
不好意思，我更新版本的时候好像是代码没有写完。于是出现了这样的错误，我昨天晚上调试的时候也出现了这样的错误。如果你有需要的话可以稍等。我调试好了后再push到GitHub上来。或者直接使用release版本

**Comment by rick-lzr** [comment]
这个项目的主要目的是为了给一个集体刷EGPA做的。但是你这个问题的话可能是puid和guid没有获取正确。你应该获取正确的两个id才行。获取id的方式是点开你要发送投票的微社区。查看你的网址如下：
http://www.yiban.cn/newgroup/indexPub/group_id/ `xxx` /puid/ `xxx`这两个参数后面的就是excel表格上的参数。你可以尝试使用正确的puid和groupid
我又重新测验了一次。代码是写完了的。我的可以运行。
![image](https://user-images.githubusercontent.com/43662748/78465781-74333200-772c-11ea-92e3-7251ef7e253d.png)
希望可以帮助到你

**Comment by chainsx** [comment]
guid和puid确实是按照图片来获取的，我对于需求呢没有太大，这是一个非常好的项目，顶一下！

**Comment by chainsx** [comment]
说错了，groupid和puid的确是按照图片那样来设置的

**Comment by rick-lzr** [comment]
那你成功没有呢？如果没有成功方便留下你的qq信息吗我可以将我本地的打包给你。

**Comment by chainsx** [comment]
谢谢，
emmm，意思是说这个项目线上线下没有同步吗？
我的QQ：1396219808

**Comment by chainsx** [comment]
why reopened?
