### ISSUE TITLE
提示getaddrinfo failed和keyErro“data”解决办法之一

### ISSUE THREAD

**Issue by Thinker152** [lzr936332553/yiban_Automation_tool#4]
![image](https://user-images.githubusercontent.com/64756495/82769055-47b2b100-9e65-11ea-95ed-f4631b294f98.png)

**Comment by Time-Stone54** [comment]
已经star

**Comment by rick-lzr** [comment]
你使用的是最新的代码版本还是发行版（release）版本呢？如果是release的话烦请到release区重新下载新的发行版。第一版已经失效了。。。新版本的版本号是V0.1.2

**Comment by Thinker152** [comment]
> 你使用的是最新的代码版本还是发行版（release）版本呢？如果是release的话烦请到release区重新下载新的发行版。第一版已经失效了

发行版的relese的
![image](https://user-images.githubusercontent.com/64756495/82769333-a88eb900-9e66-11ea-9468-a3391d151afa.png)这里只有第一版，有新的链接吗

**Comment by rick-lzr** [comment]
https://gitee.com/lzr9/yiban_Automation_tool/releases
https://github.com/SadTomlzr/yiban_Automation_tool/releases

**Comment by Thinker152** [comment]
> https://gitee.com/lzr9/yiban_Automation_tool/releases
> https://github.com/SadTomlzr/yiban_Automation_tool/releases

thanks，已收到

**Comment by Thinker152** [comment]
> > https://gitee.com/lzr9/yiban_Automation_tool/releases
> > https://github.com/SadTomlzr/yiban_Automation_tool/releases
> 
> thanks，已收到

![image](https://user-images.githubusercontent.com/64756495/82769580-c6105280-9e67-11ea-9be1-f57214ecd05f.png)
zhe这样子怎么解决？

**Comment by rick-lzr** [comment]
看不到你的图片

**Comment by Thinker152** [comment]
> 看不到你的图片

![image](https://user-images.githubusercontent.com/64756495/82769918-323f8600-9e69-11ea-8418-7b1f3ed3be64.png)
这样能看到吗

**Comment by Thinker152** [comment]
> 看不到你的图片

模拟登陆成功
获取到的用户id为:xxxxxx
已经参加过调查
获取到的动态id为:xxx
动态相关的网薪获取完成.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "yiban_Automation_tool - 发布exe版本\EGPA_script_random_num.py", line 70, in login
  File "yiban_Automation_tool - 发布exe版本\EGPA_script_random_num.py", line 208, in start
  File "yiban_Automation_tool - 发布exe版本\EGPA_script_random_num.py", line 359, in addTopic
KeyError: 'data'
这样报错 data

**Comment by rick-lzr** [comment]
你是不是今天运行过很多次了。或者你们发话题现在需要验证码？

**Comment by Thinker152** [comment]
> 你是不是今天运行过很多次了。或者你们发话题现在需要验证码？

之前尝试运行了很多次，都是报错，发投票有两个选项，一个是选择认证码，一个是不选择，群里发言不需要验证码

**Comment by rick-lzr** [comment]
![$Y DP$UG{2_HG`146B)~$R0](https://user-images.githubusercontent.com/43662748/82770832-90219d00-9e6c-11ea-848b-f549647310df.png)
注意puid和group_id的获取该issue的第二种情况是因此出现的。
